spring.application.name=Student
spring.datasource.url=jdbc:postgresql://localhost:5432/jarvis
spring.datasource.username=postgres
spring.datasource.password=1409

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
